### ISSUE TITLE
Add support for downloading ansible usage information and hosts modified

### ISSUE THREAD

**Issue by starnold-redhat** [C-RH-C/crhc-cli#179]
Add an extra option to download ansible usage information from ansible insights

can use this api call
'https://console.redhat.com/api/tower-analytics/v1/host_explorer/?sort_by=host_count&limit=25&offset=0' -d '{"group_by": "org"}'

**Comment by waldirio** [comment]
Hello @starnold-redhat 

It sounds like a plan!!

PR #186 updated.

Thank you
Waldirio
