### ISSUE TITLE
ts dump downloads stale and current systems - need an option to download just current systems

### ISSUE THREAD

**Issue by starnold-redhat** [C-RH-C/crhc-cli#184]
When using the cloud, it is possible to create a lot of stale systems in c.r.h.c. It would be very useful to have an option to only dump the current systems, as this would save a lot of time i the download, and also make the hcs-collector more efficient.

In one of my customers, they have 36k systems in total, but only 12k are current.  So this feature would make a significant improvement in performance.

Proposed command line would be 
ts dump_current

**Comment by waldirio** [comment]
Hello @starnold-redhat 

Tested and all the information are in the PR.

It's working as expected.

Thank you!
Waldirio
