### ISSUE TITLE
SWATCH api has been deprecated

### ISSUE THREAD

**Issue by starnold-redhat** [C-RH-C/crhc-cli#200]
Need to swap over the swatch api from https://console.redhat.com/api/rhsm-subscriptions/v1/hosts/products to /subscriptions/products/{product_id}.

Also we can then pick up the category field - which indicates whether we think its virtual, a hypervisor, physical or running in cloud

**Comment by waldirio** [comment]
Thank you @starnold-redhat 

I got this error just today, I came to open a new issue and just got it.

I'm not sure if you have already some changes, if not, no problem. I'll start working on this one now.

Thank you!
Waldirio

**Comment by waldirio** [comment]
Fixed.
