### ISSUE TITLE
Is there a version of crhc-linux-64 for ARM ?

### ISSUE THREAD

**Issue by fabienfigueras** [C-RH-C/crhc-cli#247]
Hello !

Is there a version of crhc-linux-64 for ARM available ?

Or

How to buld one with RHEL9 for ARM ?

Thank for your help

**Comment by waldirio** [comment]
Hello @fabienfigueras 

Please, check the steps [here](https://crhc-cli.readthedocs.io/en/latest/contribution.html)

Checking it now, I need to update this doc, but you can proceed as below

```
$ git clone https://github.com/C-RH-C/crhc-cli.git
$ cd crhc-cli
$ python3 -m venv ~/.virtualenv/crhc-cli
$ source ~/.virtualenv/crhc-cli/bin/activate
$ pyinstaller --paths=. --onefile bin/crhc-cli
```

This should create the file `dist/crhc-cli`

Please, let me know if you have any issues/questions.

Waldirio

**Comment by fabienfigueras** [comment]
Hi Waldirio
Thank you very much those commands works fine.
You can close this issue.
Kind Regards
Fabien

**Comment by waldirio** [comment]
Hello @fabienfigueras 

Glad to know everything worked as expected. I'll keep this issue, then I'll track the change in the documentation.

Please, let me know if there is anything else you would like to see on `crhc-cli`

Thank you!
Waldirio
