### ISSUE TITLE
Covert project from Python to Ruby

### ISSUE THREAD

**Issue by chris1984** [C-RH-C/crhc-cli#31]
Python is not the best, can we change this to Ruby?

**Comment by waldirio** [comment]
Hello @chris1984, thanks for the heads up. Different from Satellite, a lot of tools under `console.redhat.com` are in python, I don't see any problem but I believe now it's a bit late. I'll check it and I'll keep you in touch.

Is there any information that can support this request? I don't believe `Python is not the best` will be a valid one! :-)

Thank you
Waldirio

**Comment by waldirio** [comment]
Hello @chris1984 

Closing this issue for now, in the future, we can build the same in ruby for fun or to practice ruby as well.

Thank you
