### ISSUE TITLE
unhandled exception in inventory list_all option

### ISSUE THREAD

**Issue by m8ram** [C-RH-C/crhc-cli#44]
During a Red Hat support call an engineer downloaded and ran crhc.
Running the `inventory list` option works but `inventroy list_all` fails:
```
 ./crhc inventory list_all
Traceback (most recent call last):
  File "crhc.py", line 10, in <module>
  File "parse/parse.py", line 207, in main_menu
  File "parse/parse.py", line 35, in inventory_sub_menu
  File "execution/execution.py", line 108, in inventory_list_all
KeyError: 'results'
[531882] Failed to execute script 'crhc' due to unhandled exception!
```
This is using python 3.6.8

This is using release 1.2.1

**Comment by waldirio** [comment]
Hello @m8ram ,

Thanks for the heads up and yea, it's already fixed in the latest version (1.3.2).

Please, download the binary from here [link](https://github.com/c-RH-C/crhc-cli/releases/latest) and the `list_all` should be working with no issues.

Thank you!
Waldirio

**Comment by m8ram** [comment]
I confirm it works with the version 1.3.2

**Comment by waldirio** [comment]
Hello @m8ram 

Thanks for the heads up. Glad to help.

I would like to share that I just released a new version, with some new features and fixes.

I hope you enjoy it.

Thank you!
