### ISSUE TITLE
Missing standard options `--help` and `--version` or `-V`

### ISSUE THREAD

**Issue by m8ram** [C-RH-C/crhc-cli#45]
Release 1.2.1 does not support or provide useful information for the standard options  `--help` and `--version` or `-V`
```
$ ./crhc --version
invalid option
$ ./crhc --help
This help!
$ ./crhc -V
invalid option
```

**Comment by waldirio** [comment]
Hello @m8ram 

Thank you, adding to our backlog.

**Comment by waldirio** [comment]
fixed.
