### ISSUE TITLE
Create the python binary for MS windows

### ISSUE THREAD

**Issue by waldirio** [C-RH-C/crhc-cli#89]

**Comment by pgarciaq** [comment]
I have built a binary for Windows. It requires updates in some of the requirements. What now?

**Comment by waldirio** [comment]
> I have built a binary for Windows. It requires updates in some of the requirements. What now?

Hello @pgarciaq thank you for the heads up. Please, if you are able to, create a new branch on your side, add the changes and push a Pull Request.

Thank you again!
Waldirio

**Comment by waldirio** [comment]
Binary already available. I'll be updating our docs to present how to clone/change/create a new binary in `MS Windows`. I'll use this issue for that.

**Comment by waldirio** [comment]
The binary is already available. I'll open another issue about the documentation to keep track of how to implement the environment in MS windows box.

Thank you @pgarciaq
